/** Template metadata for Director selection — extend as new templates ship. */
export const TEMPLATE_VIBE_TAGS: Record<string, string[]> = {
  KineticHero: ["hook", "bold", "kinetic", "glass_orb", "apple_clean"],
  BentoGrid: ["features", "density", "stripe_density", "apple_clean"],
  FeatureShowcase: ["product", "demo", "proof"],
  SplitScreen: ["comparison", "problem", "solution"],
  StatCounter: ["metrics", "social-proof", "stripe_density"],
  LogoReveal: ["brand", "outro", "cta"],
  ProductOrbit3D: ["hero", "3d", "premium"],
  DemoBrowserWalkthrough: ["ui", "walkthrough", "linear_devtool"],
  LottieOverlay: ["motion", "logo-sting"],
  IntegrationShowcase: ["partners", "trust"],
  TestimonialSpotlight: ["quote", "proof"],
  ComparisonSplit: ["contrast", "before-after"],
  OrbFieldHero: ["abstract", "energy", "apple_clean"],
  GlyphRhythm: ["pulse", "tech", "vercel_brutal"],
  Terminal: ["cli", "devtools", "linear_devtool"],
  ReceiptStack: ["transactions", "stripe_density"],
  MetricSparkline: ["data", "sparkline", "stripe_density"],
  SerifEditorial: ["editorial", "luxury", "apple_clean"],
  CursorWalkthrough: ["vision", "demo", "linear_devtool"],
  BrollCutaway: ["b-roll", "cinematic"],
  NarratorAvatar: ["avatar", "talking-head"],
};
